### ISSUE TITLE
It is not possible to join a role with spaces

### ISSUE THREAD

**Issue by benji7425** [benji7425/discord-role-assigner#4]
Currently trying to join a role with a space returns "specified parameter is not a role or snowflake"

**Comment by pseiler** [comment]
I filed this issue seconds ago. Do you fix this issue in the next days? If not I could try it and send a pull request

**Comment by benji7425** [comment]
This is actually an issue with my TypeScript upgrade on [this](https://github.com/benji7425/discord-bot-role-assigner/tree/typescript) branch, is this what you were referring to @pseiler?

**Comment by pseiler** [comment]
@benji7425  No. I'm using the bot with tag v3.4.0 and roles with spaces do not work.
Without spaces allowing roles work as expected.

**Comment by benji7425** [comment]
Roles with spaces work in v3.4.0 if you just omit the space when using the command

**Comment by pseiler** [comment]
I'll test this. Thank you :wink:

**Comment by benji7425** [comment]
Might have to solve this by implementing a basic character escape mechanic, with backslash.
Example: `@Role Assigner set-joinable role\ with\ spaces true`

**Comment by benji7425** [comment]
Thinking about this further, I don't know how I would effectively communicate this mechanism to users. I doubt they would instinctively try backslashes. It might just be best to fall back on requiring space characters to be eliminated in the command, and just assume that servers don't have both "my role" and "myrole" in their server.

**Comment by benji7425** [comment]
This does actually work fine in v4 by omitting spaces, don't know why I was confusing myself over it.
![image](https://user-images.githubusercontent.com/14295333/68519561-a037ad80-0289-11ea-8fcb-15558f584346.png)
![image](https://user-images.githubusercontent.com/14295333/68519581-c65d4d80-0289-11ea-8767-28c1bcb6b65b.png)

**Comment by pseiler** [comment]
ah very nice. Thank you very much
