### ISSUE TITLE
Add new line between listed roles

### ISSUE THREAD

**Issue by pseiler** [benji7425/discord-role-assigner#5]
Is it possible to change the output of view-roles to seperate each role with a new line instead of a comma and space?

/e: Is it possible that the bot posts the response via direct message instead of writing it to the channel? This would prevent spam everytime a user uses ```@Role Assigner view-role``` in a channel.

**Comment by benji7425** [comment]
You could update the code to achieve these yourself in the short term, otherwise I can add this to my feature list for future

**Comment by benji7425** [comment]
I have finally got around to actually releasing [v4.0.0](https://github.com/benji7425/discord-role-assigner/releases/tag/v4.0.0), which includes this change!

**Comment by pseiler** [comment]
this sounds great ;)
